// frontend/src/components/shared/WorkspaceNav.vue
<template>
  <nav :class="['workspace-nav', `workspace-nav--${layout}`]" aria-label="工作区导航">
    <button
      v-for="item in visibleItems"
      :key="item.id"
      type="button"
      :class="['workspace-nav__item', { 'is-active': item.id === activeWorkspace }]"
      @click="handleChange(item.id)"
    >
      <span class="workspace-nav__glyph" aria-hidden="true">{{ item.navGlyph || item.step || item.label?.[0] || '?' }}</span>
      <span class="workspace-nav__content">
        <em>{{ item.groupLabel || item.group || '工作区' }}</em>
        <strong>{{ item.label }}</strong>
        <small>{{ item.hint || item.summary || item.focusTitle || '' }}</small>
      </span>
    </button>
  </nav>
</template>

<script setup>
import { computed } from 'vue'
import { WORKSPACES } from '@/appConfig'

const props = defineProps({
  items: {
    type: Array,
    default: () => WORKSPACES,
  },
  activeWorkspace: {
    type: String,
    default: '',
  },
  onChangeWorkspace: {
    type: Function,
    default: null,
  },
  canShowAdmin: {
    type: Boolean,
    default: false,
  },
  layout: {
    type: String,
    default: 'rail',
  },
})

const visibleItems = computed(() => {
  return (props.items || []).filter((item) => props.canShowAdmin || item.id !== 'admin')
})

function handleChange(workspaceId) {
  props.onChangeWorkspace?.(workspaceId)
}
</script>

// frontend/src/components/WorkspaceNav.jsx
import { WORKSPACES } from "@/appConfig";

export function WorkspaceNav({
  activeWorkspace,
  onChangeWorkspace,
  canShowAdmin = false,
  layout = "inline",
  items = null,
}) {
  const visibleWorkspaces = (items || WORKSPACES).filter((workspace) => canShowAdmin || workspace.id !== "admin");

  return (
    <nav className={`workspace-nav workspace-nav--${layout}`} aria-label="工作区导航">
      {visibleWorkspaces.map((workspace, index) => {
        const active = workspace.id === activeWorkspace;
        return (
          <button
            key={workspace.id}
            type="button"
            className={`workspace-nav__item${active ? " is-active" : ""}`}
            onClick={() => onChangeWorkspace(workspace.id)}
          >
            <span className="workspace-nav__glyph" aria-hidden="true">
              {workspace.navGlyph || workspace.step || String(index + 1).padStart(2, "0")}
            </span>
            <span className="workspace-nav__content">
              {layout !== "sidebar" && workspace.groupLabel ? <em>{workspace.groupLabel}</em> : null}
              <strong>{workspace.label}</strong>
              <small>{workspace.hint}</small>
            </span>
          </button>
        );
      })}
    </nav>
  );
}
